ludus:
  - vm_name: "{{ range_id }}-ad-dc-win2022-server-x64"
    hostname: "{{ range_id }}-DC01-2022"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    domain:
      fqdn: dumpster.fire
      role: primary-dc
    roles:
      - ludus-ad-content
    role_vars:
      ludus_ad:
        ous:
          - name: US
            path: DC=dumpster,DC=fire
            description: US
          - name: Canada
            path: DC=dumpster,DC=fire
            description: "Canada, eh?"
        groups:
          - name: Sales US
            scope: global
            path: "OU=US,DC=dumpster,DC=fire"
            description: US Sales
          - name: Sales CA
            scope: global
            path: "OU=Canada,DC=dumpster,DC=fire"
            description: Canada Sales
          - name: IT
            scope: global
            path: "DC=dumpster,DC=fire"
            description: Information Technology
        users:
          - name: iraise
            firstname: Ivana
            surname: Raise
            display_name: Ivana Raise
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "US Sales Lead"
            groups:
              - Domain Users
              - Sales US
          - name: bloblaw
            firstname: Bob
            surname: Loblaw
            display_name: Bob Loblaw
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "Canada Sales Lead"
            groups:
              - Domain Users
              - Sales CA
          - name: victim
            firstname: Victor
            surname: Timmons
            display_name: Vic Timmons
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "System Engineer"
            groups:
              - Domain Users
              - IT
          - name: stabby
            firstname: Shane
            surname: Tabby
            display_name: Shane Tabby
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "IT Guy"
            groups:
              - Domain Users
              - IT
          - name: sadmin
            firstname: Sad
            surname: Admin
            display_name: Sad Admin
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "Sad Administrator"
            groups:
              - Domain Users
              - IT
              - Domain Admins
  - vm_name: "{{ range_id }}-ad-win10-21h2-enterprise-x64-1"
    hostname: "{{ range_id }}-WS01-win10"
    template: win10-21h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 21
    ram_gb: 4
    cpus: 2
    windows:
      install_additional_tools: true
      office_version: 2019
      office_arch: 64bit
    domain:
      fqdn: dumpster.fire
      role: member
  - vm_name: "{{ range_id }}-ad-win11-22h2-enterprise-x64-1"
    hostname: "{{ range_id }}-WS02-win11"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 31
    ram_gb: 4
    cpus: 2
    windows:
      install_additional_tools: true
      office_version: 2019
      office_arch: 64bit
    domain:
      fqdn: dumpster.fire
      role: member
  - vm_name: "{{ range_id }}-ad-win2019-server-x64"
    hostname: "{{ range_id }}-SRV01-win2019"
    template: win2019-server-x64-template
    vlan: 10
    ip_last_octet: 15
    ram_gb: 8
    cpus: 4
    windows:
      sysprep: false
    domain:
      fqdn: dumpster.fire
      role: member
    roles:
      - badsectorlabs.ludus_mssql