ludus:
  - vm_name: "{{ range_id }}-DC01"
    hostname: "DC01"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 11
    ram_gb: 8
    ram_min_gb: 1
    cpus: 4
    windows:
      sysprep: true
    domain:
      fqdn: dumpster.fire 
      role: primary-dc
    roles:
      - ludus-ad-content
    role_vars:
      ludus_ad:
        ous:
          - name: US
            path: DC=dumpster,DC=fire
            description: US
          - name: Canada
            path: DC=dumpster,DC=fire
            description: "Canada, eh?"
        groups:
          - name: Sales US
            scope: global
            path: "OU=US,DC=dumpster,DC=fire"
            description: US Sales
          - name: Sales CA
            scope: global
            path: "OU=Canada,DC=dumpster,DC=fire"
            description: Canada Sales
          - name: IT
            scope: global
            path: "DC=dumpster,DC=fire"
            description: Information Technology
        users:
          - name: iraise
            firstname: Ivana
            surname: Raise
            display_name: Ivana Raise
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "US Sales Lead"
            groups:
              - Domain Users
              - Sales US
          - name: bloblaw
            firstname: Bob
            surname: Loblaw
            display_name: Bob Loblaw
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "Canada Sales Lead"
            groups:
              - Domain Users
              - Sales CA
          - name: victim
            firstname: Victor
            surname: Timmons
            display_name: Vic Timmons
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "System Engineer"
            groups:
              - Domain Users
              - IT
          - name: stabby
            firstname: Shane
            surname: Tabby
            display_name: Shane Tabby
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "IT Guy"
            groups:
              - Domain Users
              - IT
          - name: sadmin
            firstname: Sad
            surname: Admin
            display_name: Sad Admin
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "Sad Administrator"
            groups:
              - Domain Users
              - IT
              - Domain Admins
          - name: ftpsvc
            firstname: FTP
            surname: Service Account
            display_name: FTP Service Account
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "FTP Service Account"
            groups:
              - Domain Users
          - name: iissvc
            firstname: IIS
            surname: Service Account
            display_name: IIS Service Account
            password: "P@$$w0rd"
            path: "DC=dumpster,DC=fire"
            decription: "IIS Service Account"
            groups:
              - Domain Users
  - vm_name: "{{ range_id }}-SRV01"
    hostname: "SRV01"
    template: win2022-server-x64-template
    vlan: 10
    ip_last_octet: 15
    ram_gb: 4
    ram_min_gb: 1
    cpus: 2
    windows:
      sysprep: true
    domain:
      fqdn: dumpster.fire
      role: member
  - vm_name: "{{ range_id }}-WS01"
    hostname: "WS01"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 51
    ram_gb: 8
    ram_min_gb: 1
    cpus: 4
    windows:
      chocolatey_packages:
        - vscodium
        - googlechrome
      chocolatey_ignore_checksums: true # Chrome updates faster than choco package hash updates
      install_additional_tools: true
      office_version: 2021
      office_arch: 64bit
      sysprep: true
    domain:
      fqdn: dumpster.fire
      role: member
  - vm_name: "{{ range_id }}-WS02"
    hostname: "WS02"
    template: win11-22h2-x64-enterprise-template
    vlan: 10
    ip_last_octet: 52
    ram_gb: 8
    cpus: 4
    windows:
      chocolatey_packages:
        - googlechrome
      chocolatey_ignore_checksums: true # Chrome updates faster than choco package hash updates
      install_additional_tools: true
      office_version: 2021
      office_arch: 64bit
      sysprep: true
    domain:
      fqdn: dumpster.fire
      role: member

network:
  inter_vlan_default: REJECT
  rules:
    - name: Only allow windows to kali on 443
      vlan_src: 10
      vlan_dst: 99
      protocol: tcp
      ports: 443
      action: ACCEPT
    - name: Only allow windows to kali on 80
      vlan_src: 10
      vlan_dst: 99
      protocol: tcp
      ports: 80
      action: ACCEPT
    - name: Only allow windows to kali on 8080
      vlan_src: 10
      vlan_dst: 99
      protocol: tcp
      ports: 8080
      action: ACCEPT
    - name: Allow kali to all windows
      vlan_src: 99
      vlan_dst: 10
      protocol: all
      ports: all
      action: ACCEPT