- name: DC tasks - register SPNs for iissvc
  ansible.windows.win_shell: |
    setspn.exe /s "HTTP/SRV01" "dumpster\iissvc"
    setspn.exe /s "HTTP/SRV01.dumpster.fire" "dumpster\iissvc"
  when: inventory_hostname == range_id + '-DC01'

- name: SRV01 tasks - install IIS and RSAT-AD-PowerShell
  ansible.windows.win_feature:
    name:
      - RSAT-AD-PowerShell
      - Web-Windows-Auth
      - Web-Server
    state: present
    include_management_tools: true
  when: inventory_hostname == range_id + '-SRV01'

- name: SRV01 tasks - disable anonymous authentication on Default Web Site
  ansible.windows.win_shell: |
    Import-Module WebAdministration
    Set-WebConfigurationProperty `
      -filter /system.WebServer/security/authentication/AnonymousAuthentication `
      -name enabled -value $false `
      -location "IIS:\Sites\Default Web Site"
  when: inventory_hostname == range_id + '-SRV01'

- name: SRV01 tasks - enable Windows authentication on Default Web Site
  ansible.windows.win_shell: |
    Import-Module WebAdministration
    Set-WebConfigurationProperty `
      -filter /system.WebServer/security/authentication/WindowsAuthentication `
      -name enabled -value $true `
      -location "IIS:\Sites\Default Web Site"
  when: inventory_hostname == range_id + '-SRV01'

- name: SRV01 tasks - configure DefaultAppPool to run as iissvc
  ansible.windows.win_shell: |
    Import-Module WebAdministration
    Set-ItemProperty "IIS:\AppPools\DefaultAppPool" -name "processModel.identityType" -value "SpecificUser"
    Set-ItemProperty "IIS:\AppPools\DefaultAppPool" -name "processModel.userName" -value "dumpster\iissvc"
    Set-ItemProperty "IIS:\AppPools\DefaultAppPool" -name "processModel.password" -value 'P@$$w0rd'
    Set-WebConfigurationProperty `
      -filter /system.WebServer/security/authentication/WindowsAuthentication `
      -name useAppPoolCredentials -value $true `
      -location "IIS:\Sites\Default Web Site"
  when: inventory_hostname == range_id + '-SRV01'

- name: SRV01 tasks - iisreset
  ansible.windows.win_shell: iisreset
  when: inventory_hostname == range_id + '-SRV01'